# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: PHYS/ASTR 7730
author: Yao-Yuan Mao (University of Utah)
copyright: "2024"
logo: logo.png
exclude_patterns: ["backup"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/yymao/phys7730  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  baseurl: https://yymao.github.io/phys7730/

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - strikethrough
    - substitution
    - tasklist
