# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: PHYS/ASTR 7730
author: Yao-Yuan Mao (University of Utah)
copyright: "2024"
logo: logo.png
exclude_patterns: ["excluded", "build.sh", ".gitignore"]

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - strikethrough
    - substitution
    - tasklist

html:
  use_issues_button: true
  baseurl: https://yymao.github.io/phys7730/
  extra_footer: Statistical and Computational Methods in Physics and Astronomy

repository:
  url: https://github.com/yymao/phys7730
  branch: main

bibtex_bibfiles:
    - references.bib

sphinx:
  config:
    html_extra_path: ["assets"]
    language: en-US
