# environment.yml for 7730

name: "7730"
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.11
  - corner >=2.2
  - emcee >=3.1
  - jupyterlab >=4.1
  - jupyterlab-myst >=2.3
  - matplotlib-base >=3.8
  - nbconvert-core >=7.14
  - numpy >=1.26
  - pandas >=2.2
  - scikit-learn >=1.4
  - scipy >=1.12
