name: deploy-book

on:
  push:
    branches:
    - main
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "pyproject.toml"
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install the project
      run: uv sync --extra docs
    - name: Build spring2024
      run: uv run jupyter-book build spring2024/
    - name: Build current
      run: uv run jupyter-book build --all .
    - name: Move spring2024
      run: |
        rm -rf _build/html/spring2024
        cp -r spring2024/_build/html _build/html/spring2024
    - uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
