name: deploy-book

on:
  push:
    branches:
    - main
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        enable-cache: true
    - uses: actions/setup-python@v7
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: uv sync
    - name: Build current semester
      run: uv run jupyter-book build --all .
    - name: Restore cached past semesters
      id: cache
      uses: actions/cache/restore@v6
      with:
        path: |
          _build/html/spring2024
        key: cache-past-semesters-
    - name: Check if any changes in past semesters
      uses: dorny/paths-filter@v4
      id: changes
      with:
        filters: |
          spring2024:
            - 'spring2024/**'
    - name: Build Spring 2024
      if: ${{ (steps.changes.outputs.spring2024 == 'true') || (steps.cache.outputs.cache-hit == '') }}
      run: |
        uv run jupyter-book build --all spring2024/
        rm -rf _build/html/spring2024
        mv spring2024/_build/html _build/html/spring2024
    - name: Save past semesters
      if: ${{ (steps.changes.outputs.spring2024 == 'true') || (steps.cache.outputs.cache-hit == '') }}
      uses: actions/cache/save@v6
      with:
        path: |
          _build/html/spring2024
        key: cache-past-semesters-${{ github.run_id }}
    - uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
