name: deploy-book

on:
  push:
    branches:
    - main
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set variables
      id: my-vars
      run: |
        echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        echo "env-name=7730" >> $GITHUB_OUTPUT
    - name: Cache conda packages
      uses: actions/cache@v4
      with:
        path: ~/conda_pkgs_dir
        key: conda-packages
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: ${{ steps.my-vars.outputs.env-name }}
        miniforge-version: latest
        use-only-tar-bz2: true
    - name: Cache conda environments
      uses: actions/cache@v4
      id: cache-conda-envs
      with:
        path: ${{ env.CONDA }}/envs
        key: conda-envs-${{ steps.my-vars.outputs.today }}-${{ hashFiles('assets/environment.yml') }}
    - name: Update conda environment
      if: steps.cache-conda-envs.outputs.cache-hit != 'true'
      run: |
         mamba env update -n ${{ steps.my-vars.outputs.env-name }} -f assets/environment.yml
         mamba install -y jupyter-book
    - name: Build the book
      run: |
        jupyter-book build --all .
    - name: Push to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
