name: deploy-book

on:
  push:
    branches:
    - main
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set variables
      id: my-vars
      run: |
        ENV_FNAME=assets/environment.yml
        ENV_HASH=$(/bin/sha256sum $ENV_FNAME)
        echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        echo "envfile=$ENV_FNAME" >> $GITHUB_OUTPUT
        echo "envhash=${ENV_HASH## *}" >> $GITHUB_OUTPUT
        echo "envname=7730" >> $GITHUB_OUTPUT
    - name: Cache conda packages
      uses: actions/cache@v4
      with:
        path: ~/conda_pkgs_dir
        key: conda-pkgs-${{ steps.my-vars.outputs.envhash }}
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: ${{ steps.my-vars.outputs.envname }}
        miniforge-version: latest
        use-only-tar-bz2: true
    - name: Cache conda environments
      uses: actions/cache@v4
      id: cache-conda-envs
      with:
        path: ${{ env.CONDA }}/envs
        key: conda-envs-${{ steps.my-vars.outputs.today }}-${{ steps.my-vars.outputs.envhash }}
    - name: Update conda environment
      if: steps.cache-conda-envs.outputs.cache-hit != 'true'
      run: mamba env update -n ${{ steps.my-vars.outputs.envname }} -f ${{ steps.my-vars.outputs.envfile }}
    - name: Build the book
      shell: bash -el {0}
      run: |
        conda activate ${{ steps.my-vars.outputs.envname }}
        jupyter-book build --all .
    - name: Push to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
