name: deploy-book

on:
  push:
    branches:
    - main
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: assets/environment.yml
        miniforge-version: latest
    - name: Build the book
      run: |
        jupyter-book build --all .
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
