name: deploy-book

on:
  push:
    branches:
    - main
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache conda
      uses: actions/cache@v3
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ hashFiles('assets/environment.yml') }}
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: "7730"
        environment-file: assets/environment.yml
        miniforge-version: latest
        use-only-tar-bz2: true
    - name: Build the book
      shell: bash -el {0}
      run: |
        jupyter-book build --all .
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
