name: deploy-book

on:
  push:
    branches:
    - main
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install Python dependencies
      run: pip install -r requirements.txt
    - name: Build spring2024
      run: jupyter-book build --all spring2024/
    - name: Build current
      run: jupyter-book build --all .
    - name: Move spring2024
      run: |
        rm -rf _build/html/spring2024
        mv spring2024/_build/html _build/html/spring2024
    - uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
